spring:
  application:
    name: resource-app
  config:
    import:
      - optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:resource_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:0909}
    driver-class-name: org.postgresql.Driver


springdoc:
  swagger-ui:
    enabled: false
    oauth:
      client-id: frontend-client
      use-pkce-with-authorization-code-grant: true
      scopes: openid profile email

server:
  port: 8082

custom-header-names:
  auth:
    permissions:
      "X-Auth-Permissions"
    roles:
      "X-Auth-Roles"

services:
  resource:
    url: ${RESOURCE_SERVICE_URL:http://localhost:8082}