spring:
  application:
    name: resource-app
  config:
    import:
      - optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:resource_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:0909}
    driver-class-name: org.postgresql.Driver

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    producer:
      properties:
        transaction.timeout.ms: ${KAFKA_TRANSACTION_TIMEOUT:60000}
        spring.json.trusted.packages: uz.uptimehub.resource.kafka.dto
      key-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      properties:
        spring.json.trusted.packages: "*"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      group-id: resource
      auto-offset-reset: earliest
      isolation-level: read_committed
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      max-poll-records: 10000

app:
  kafka:
    concurrency: 1
    topics:
      resource-index: ${KAFKA_TOPIC_RESOURCE_INDEX:resource.resource-index}

springdoc:
  swagger-ui:
    enabled: false
    oauth:
      client-id: frontend-client
      use-pkce-with-authorization-code-grant: true
      scopes: openid profile email

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: 8082

custom-header-names:
  auth:
    permissions:
      "X-Auth-Permissions"
    roles:
      "X-Auth-Roles"

services:
  resource:
    url: ${RESOURCE_SERVICE_URL:http://localhost:8082}